name: 'Clean Data Quality Check'
description: 'AI-powered data quality analysis for ML datasets. Detect label errors, duplicates, outliers, and bias.'
author: 'Clean Team'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  file:
    description: 'Path to the dataset file (CSV, Parquet, or JSON)'
    required: true
  label-column:
    description: 'Name of the label column'
    required: false
    default: 'label'
  fail-below:
    description: 'Fail the check if quality score is below this threshold (0-100)'
    required: false
    default: '0'
  detectors:
    description: 'Comma-separated list of detectors to run (label_errors,duplicates,outliers,imbalance,bias)'
    required: false
    default: 'all'
  output-format:
    description: 'Output format (text, json, markdown)'
    required: false
    default: 'markdown'
  output-file:
    description: 'Path to save the report (optional)'
    required: false
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  clean-version:
    description: 'Version of clean-data-quality to install'
    required: false
    default: 'latest'

outputs:
  quality-score:
    description: 'Overall data quality score (0-100)'
    value: ${{ steps.analyze.outputs.quality_score }}
  label-errors:
    description: 'Number of label errors detected'
    value: ${{ steps.analyze.outputs.label_errors }}
  duplicates:
    description: 'Number of duplicates detected'
    value: ${{ steps.analyze.outputs.duplicates }}
  outliers:
    description: 'Number of outliers detected'
    value: ${{ steps.analyze.outputs.outliers }}
  passed:
    description: 'Whether the quality check passed (true/false)'
    value: ${{ steps.analyze.outputs.passed }}
  report:
    description: 'Full analysis report'
    value: ${{ steps.analyze.outputs.report }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Clean
      shell: bash
      run: |
        if [ "${{ inputs.clean-version }}" = "latest" ]; then
          pip install clean-data-quality
        else
          pip install clean-data-quality==${{ inputs.clean-version }}
        fi

    - name: Run Data Quality Analysis
      id: analyze
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
        INPUT_LABEL_COLUMN: ${{ inputs.label-column }}
        INPUT_FAIL_BELOW: ${{ inputs.fail-below }}
        INPUT_DETECTORS: ${{ inputs.detectors }}
        INPUT_OUTPUT_FORMAT: ${{ inputs.output-format }}
        INPUT_OUTPUT_FILE: ${{ inputs.output-file }}
      run: |
        python ${{ github.action_path }}/run_check.py

    - name: Add PR Comment
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = '${{ steps.analyze.outputs.report_file }}';
          
          if (fs.existsSync(reportPath)) {
            const report = fs.readFileSync(reportPath, 'utf8');
            const passed = '${{ steps.analyze.outputs.passed }}' === 'true';
            const icon = passed ? '✅' : '❌';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## ${icon} Data Quality Report\n\n${report}`
            });
          }
