# These are supported funding model platforms

github: [clean-data]
# open_collective: clean
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name
# custom: # Replace with up to 4 custom sponsorship URLs
