name: Bug Report
description: Report a bug in Clean
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I call analyze(), I get an unexpected error...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Import clean
        2. Create DatasetCleaner with...
        3. Call analyze()
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages if applicable.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal reproducible example
      description: Please provide a minimal code example that reproduces the issue.
      render: python
      placeholder: |
        from clean import DatasetCleaner
        import pandas as pd

        df = pd.DataFrame(...)
        cleaner = DatasetCleaner(data=df, label_column='label')
        report = cleaner.analyze()

  - type: input
    id: version
    attributes:
      label: Clean version
      description: Run `python -c "import clean; print(clean.__version__)"` to get this.
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: python
    attributes:
      label: Python version
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
